### ISSUE TITLE
contact page

### ISSUE THREAD

**Issue by Lilicod** [202306-NEA-DZ-FEW/online-Therapist#14]
**Task title**
contact page

**Task description**
creat the contact us page

**Subtasks**

- [x] Type of contact selection section where the user can select the inquiry type.

- [x] Contact Form : Implement a user-friendly contact form with fields for users to enter their name, email address, and message.

- [x] Submission Handling : Set up a mechanism to process and manage incoming user inquiries. 

- [x] Email Integration : Configure the contact form to send an email confirmation to users upon successful submission. This email should provide a reference number or any other relevant details.

- [x] location section

- [x] Contact thanks page : After successful form submission, display a confirmation page or message to assure users that their inquiry or feedback has been received.

**Screenshots**
![contact page](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/7ef63bf9-c4aa-4246-abad-830434a1a033)
![thanks](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/2d5bbcce-2dda-40ab-8936-83694087c1a0)

**Link to the component on Figma**
Contact page https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?type=design&node-id=2-5399&mode=design&t=l1V3IyeaM4ljOhfK-4

Thank you page https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?node-id=2%3A5356&mode=dev

**Comment by M07am3dM** [comment]
Done.
