### ISSUE TITLE
Sign up page

### ISSUE THREAD

**Issue by Lilicod** [202306-NEA-DZ-FEW/online-Therapist#16]
**Task title**
Sign up page

**Task description**
the Sign-Up page will support multiple sign-up methods including email, Facebook, and Google authentication using Firebase. Users will have the flexibility to choose their preferred method, making the sign-up process more accessible and user-centric.  

**Subtasks**
- [x] Email Sign-up : Implement Firebase's email/password authentication. Ensure that the user receives a verification email and that we securely store user data in Firebase.

- [x] Facebook Sign-up : Integrate Firebase with Facebook authentication. This will enable users to sign up using their Facebook accounts. This should be a seamless process and provide us with basic user data.

- [x] Google Sign-up : Implement Firebase's Google authentication, giving users the option to use their Google accounts for sign-up. Securely manage the obtained user data.

- [ ] User Data Consistency : Ensure that, regardless of the sign-up method, user data is stored consistently in Firebase.

- [x] Sign up thanks page

- [x] Add translation

- [x] Responsive design

**Screenshots**
![sign up](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/0886d49b-e946-4476-8b97-758d293ed127)
![signup thanks](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/24423b0b-d108-4712-b46d-4f9787ee824c)

**Link to the component on Figma**
https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?type=design&node-id=2-6529&mode=design&t=3WJyDJ9tmMfJOBVl-4
