### ISSUE TITLE
user profile page

### ISSUE THREAD

**Issue by Lilicod** [202306-NEA-DZ-FEW/online-Therapist#21]
**Task title**
user profile page

**Task description**
develop user profile page, enabling registered users to manage their personal information,

**Subtasks**

- [x] Users can view and edit their personal information
- [x] Display user-specific data, such as their name, email, etc.
- [x] Create Edit thanks.

**Screenshots**
![Capture d’écran 2023-10-14 203942](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/0e70d723-016e-498b-9d30-e53849027d40)
![Capture d’écran 2023-10-14 204110](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/33d03ee0-1ea2-45f6-bc8a-0bcdb3e38466)

**Link to the component on Figma**
https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?type=design&node-id=2-5731&mode=design&t=iYcMyvxa9t3sNrbw-4

**Comment by M07am3dM** [comment]
This issue are closed, look PR #110 .
