### ISSUE TITLE
Home page section 1 : Hero

### ISSUE THREAD

**Issue by M07am3dM** [202306-NEA-DZ-FEW/online-Therapist#22]
**Subtask title**
Main Section

**Task description**
- [x] Contain slides of main pictures.
- [x] Headline within the slides.
- [x] Subheadline within the siledes.
- [x] Button for booking an appointment.

**Screenshots**
![Screenshot 2023-10-19 102314](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/138310536/5f5c0772-3302-4be8-9279-e2eb4be6f44b)

**Link to the component on Figma**
https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?node-id=48%3A30&mode=dev

**Comment by M07am3dM** [comment]
Done.
