### ISSUE TITLE
Home page section 2 : Book an appointment

### ISSUE THREAD

**Issue by M07am3dM** [202306-NEA-DZ-FEW/online-Therapist#23]
**Subtask title**
Appointement section

**Task description**

- [x] Contain a header.
- [x] Contain images of therapists.
- [x] Contain a paragraph about why you should trust the online therapy.
- [x] Contain a booking appointment button's.

**Screenshots**
![Screenshot 2023-10-19 102250](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/138310536/990f7fb8-8a3f-454b-aee9-3b9745416fe7)

**Link to the component on Figma**
https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?node-id=48%3A36&mode=dev

**Comment by M07am3dM** [comment]
All the requirements are done.
