### ISSUE TITLE
Buy Ticket

### ISSUE THREAD

**Issue by Lilicod** [202306-NEA-DZ-FEW/online-Therapist#32]
**Task title**
Buy Ticket

**Task description**
 This page allows users to select their preferred payment card and proceed with purchasing a ticket.

**Subtasks**

- [x] Card Selection: Users should be able to select from their saved payment cards. The page must display a list of cards associated with their account.
- [x] Confirmation: Once users confirm their selection, there should be a confirmation message.
- [x] Create Ticket thanks page.

**Screenshots**
![Capture d’écran 2023-10-15 004635](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/e0a1fd65-5b22-4b0b-ad8a-7604624b52ef)
![Capture d’écran 2023-10-15 004653](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/82119c59-6ab6-4fb5-b4ed-e483a6d0d24c)

**Link to the component on Figma**
https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?type=design&node-id=2-6686&mode=design&t=iYcMyvxa9t3sNrbw-4
