### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by Lilicod** [202306-NEA-DZ-FEW/online-Therapist#4]
**Task title**
Project structure

**Task description**
Set the project files structure

**Subtasks**

- [x] Creat the components folder
- [x] Creat the Navbar component file
- [x] Creat the Footer component file
- [x] Creat the test files for each component
